### ISSUE TITLE
System Downtime

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/status#6]
We are experiencing a system downtime, this is being addressed. The inconvenience is regretted.

**Comment by vishnu-narayanan** [comment]
We have identified the issue and working on a fix.

**Comment by sojan-official** [comment]
The impact was due to an unexpected burst of traffic from our third-party messaging channels, which impacted the performance of our database and caching layer.  This led to a service outage for many of our cloud customers.

We have identified the bottlenecks and have applied upgrades to avoid further impact. We will be working on further reinforcements to prevent future occurrences.
